apiVersion: v1
kind: Pod
metadata:
  name: tea-app
spec:
  containers:
  - name: tea-container
    image: devopsprofile/tea
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim

  
